### ISSUE TITLE
Add check for for email validation

### ISSUE THREAD

**Issue by davidmroth** [insertish/rauth#32]
There doesn't seem to be a check to validate if email has be verified when `EmailVerification` has been enabled:

https://github.com/insertish/rauth/blob/157263ffcbd6cb1073e288b215db227634c4c29a/src/logic/auth.rs#L254-L281

I'm using the latest version of the Revolt Chat app, and email verification does not work. Users are able to login before completing the email verification step:
https://github.com/revoltchat/delta/blob/997d1fffc032719bf42632af2805d1f69de8e428/src/main.rs#L88

I also don't see where `UnverifiedAccount` Error is being raised within the code:

https://github.com/insertish/rauth/blob/775a6f3ffb9ffc0e382af32fac2924e9a707e890/src/web/session/login.rs#L36-L86

Created pull request: https://github.com/insertish/rauth/pull/33

_**note**: never programmed in Rust before, but hopefully this will shortcut the process of getting this issue resolved_

**Comment by insertish** [comment]
Closed in 77c71a6b917c3aa13d2c15828e83d81dd313680a.
